name: Deply to web.

on:
  push:
    paths:
      - '*'
    branches:
      - 'main'

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.PORT }}
          source: "index.html"
          target: /var/www/html/
          