name: Deply to web.

on:
  push:
    paths:
      - '*'
    branches:
      - 'main'

jobs:
  web-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy folder with build to the remote server
        run: |
          scp index.html ${{ secrets.SSH_USER }}@${{ secrets.SERVER }}:/var/www/html/index.html
         